export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"

//Carts
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const INCREASE_CART_ITEM_QTY = "INCREASE_CART_ITEM_QTY"
export const DECREASE_CART_ITEM_QTY = "DEREASE_CART_ITEM_QTY"
export const CLEAR_CART = "CLEAR_CART"

//categories
export const GET_WOMENS_CLOTHING = "GET_WOMENS_CLOTHING"
export const GET_MENS_CLOTHING = "GET_MENS_CLOTHING"
export const GET_JEWELLERIES = "GET_JEWELLERIES"
export const GET_ELECTRONICS = "GET_ELECTRONICS"