export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"

//User variable
export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const SET_LOGIN = "SET_LOGIN"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const ADD_TO_ORDERS = "ADD_TO_ORDERS"

//Carts
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const INCREASE_CART_ITEM_QTY = "INCREASE_CART_ITEM_QTY"
export const DECREASE_CART_ITEM_QTY = "DEREASE_CART_ITEM_QTY"
export const CLEAR_CART = "CLEAR_CART"
export const SET_COUPON_VALUE = "SET_COUPON_VALUE"

//Wish List
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"

//categories
export const GET_WOMENS_CLOTHING = "GET_WOMENS_CLOTHING"
export const GET_MENS_CLOTHING = "GET_MENS_CLOTHING"
export const GET_JEWELLERIES = "GET_JEWELLERIES"
export const GET_ELECTRONICS = "GET_ELECTRONICS"
export const GET_RELATED_PRODUCTS = "GET_RELATED_PRODUCTS"

// website settings
export const NAVBAR_TOGGLE = "NAVBAR_TOGGLE"
export const CLOSE_NAVBAR = "CLOSE_NAVBAR"
